<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_CA HNG CA BN</name>
   <tag></tag>
   <elementGuidId>62659ad1-19b9-4a86-ab21-5ae96c9dd024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.MuiTypography-root.MuiTypography-h3.MuiTypography-colorTextSecondary.MuiTypography-gutterBottom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>b735dd02-ff4f-4057-9d2f-c5e9dfba95b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h3 MuiTypography-colorTextSecondary MuiTypography-gutterBottom</value>
      <webElementGuid>2e3e87cf-04ae-41ac-8ad0-1ff06c98ad66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CỬA HÀNG CỦA BẠN</value>
      <webElementGuid>8b2ee63b-0b22-46f9-ba16-427cf04d3d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root jss394&quot;]/div[@class=&quot;MuiBox-root jss406 jss400&quot;]/div[@class=&quot;MuiPaper-root jss401 MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiBox-root jss407 jss402&quot;]/h3[@class=&quot;MuiTypography-root MuiTypography-h3 MuiTypography-colorTextSecondary MuiTypography-gutterBottom&quot;]</value>
      <webElementGuid>285ddb8d-9911-497e-b670-703faac3d87b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/h3</value>
      <webElementGuid>aad531c5-0961-4c25-9790-64a20c87cbbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[1]/preceding::h3[1]</value>
      <webElementGuid>4a90e862-b42b-4719-bfda-2341fb0b53fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CỬA HÀNG CỦA BẠN']/parent::*</value>
      <webElementGuid>ddbeca00-e080-4ab0-9413-b9ba9e19b312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>9125d588-336f-4466-b32e-7e8c6b830ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'CỬA HÀNG CỦA BẠN' or . = 'CỬA HÀNG CỦA BẠN')]</value>
      <webElementGuid>50e4b8e1-67a7-478b-b6bf-6ede225dacc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
