<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_ng nhp</name>
   <tag></tag>
   <elementGuidId>b037533c-dc76-4b21-bdcb-266d6b5fe2ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.MuiTypography-root.MuiTypography-h5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>7cf2169a-a84b-4138-b542-807731e876d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h5</value>
      <webElementGuid>5fb2e2ba-61aa-45d5-a288-0d4d685e12c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng nhập</value>
      <webElementGuid>68ce790e-f763-404f-bc81-3311739e2615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root jss394&quot;]/div[@class=&quot;MuiBox-root jss406 jss400&quot;]/div[@class=&quot;MuiPaper-root jss401 MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiBox-root jss407 jss402&quot;]/h5[@class=&quot;MuiTypography-root MuiTypography-h5&quot;]</value>
      <webElementGuid>93514a00-6945-4c3e-ad82-c7835c944b8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/h5</value>
      <webElementGuid>3466c333-46d1-4a74-9b6e-6040d6161b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CỬA HÀNG CỦA BẠN'])[1]/following::h5[1]</value>
      <webElementGuid>0b446c5e-2d2c-42af-a71f-7715abaed018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng nhập']/parent::*</value>
      <webElementGuid>2ba8b6fe-deac-484e-8e10-e932faa46b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>91a37065-975a-4826-9579-8b639e1acad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Đăng nhập' or . = 'Đăng nhập')]</value>
      <webElementGuid>ea3b3743-f17c-4c7b-b3b2-126612826352</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
