<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Chi nhnh_mui-1020</name>
   <tag></tag>
   <elementGuidId>419bbe0a-6e05-47e4-be8d-7a93002fa253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-1020</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-1020']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a367d6b0-0cdd-49e8-96d2-e7301f4bbd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>61517bc7-4544-4409-a2c1-21471288010c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3120e31b-95bb-4666-a50a-1c6a504128bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm nhà cung cấp</value>
      <webElementGuid>b0381af8-39a6-4ede-9a4d-3741be334c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8505619-537b-4113-af37-802a7f74fb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input MuiAutocomplete-input MuiAutocomplete-inputFocused MuiInputBase-inputAdornedStart MuiInputBase-inputAdornedEnd</value>
      <webElementGuid>c34625f9-a96c-4ec5-b28c-47d886d623b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>b5000286-c314-49e5-9cb2-5c64d2d16157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>113a9022-0f21-473a-9795-8ffce2430604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5075ef8a-4e78-4282-9e5e-3a6ddc194fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-1020</value>
      <webElementGuid>453a7436-fc68-4728-a6de-29b9d675e0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mui-1020-popup</value>
      <webElementGuid>6e3022ec-b596-48d5-9857-e927e64a81ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-1020&quot;)</value>
      <webElementGuid>15fc86bd-1c15-406e-a90f-39c021e6805b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-1020']</value>
      <webElementGuid>ddae2ee4-1a8b-4e60-a7e3-8e67e6171e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>70c3748b-39d7-4ad8-8e30-08b12bf7befb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>e96e5e44-4f6c-47dc-925c-851c2deb9381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tìm nhà cung cấp' and @type = 'text' and @id = 'mui-1020']</value>
      <webElementGuid>95245f2e-faee-4b4e-ad5e-9f5d752ab8c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
