<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_0938919001</name>
   <tag></tag>
   <elementGuidId>bc460dd3-ed00-4779-b0f0-07e839808943</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-1020-option-1 > div.MuiGrid-root.MuiGrid-container.MuiGrid-justify-content-xs-space-between > p.MuiTypography-root.MuiTypography-body1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-1020-option-1']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>75f5c1ba-4bcb-4dea-bc36-6d11bc04682d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1</value>
      <webElementGuid>1008c3ea-edb5-4676-8644-bfca2721d2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0938919001</value>
      <webElementGuid>ab80b230-5458-4ca0-bcd2-ab281f38c592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-1020-option-1&quot;)/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-justify-content-xs-space-between&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body1&quot;]</value>
      <webElementGuid>dbf681df-6088-483d-897c-166a466678b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mui-1020-option-1']/div/p</value>
      <webElementGuid>9ba14f3a-6265-4083-9e77-9369d1441a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Le'])[1]/following::p[1]</value>
      <webElementGuid>0ae01b24-7e1c-42c8-bfd0-d49dd4f7391f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Le1'])[1]/following::p[2]</value>
      <webElementGuid>6035ba28-820b-4a5d-9c7d-087aa059d884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0938919001']/parent::*</value>
      <webElementGuid>ae11ce03-a9b6-4256-80c5-35afb6126546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/p</value>
      <webElementGuid>3e157aa3-ed4e-4473-b113-2259873d2cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '0938919001' or . = '0938919001')]</value>
      <webElementGuid>0a9e9738-e7c4-43ce-8eaf-ad10b274c167</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
