<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Danh mc_MuiSvgIcon-root</name>
   <tag></tag>
   <elementGuidId>bc9bc328-8f1e-440f-bfac-902b39f17167</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiAvatar-root.MuiAvatar-rounded.jss695.MuiAvatar-colorDefault > svg.MuiSvgIcon-root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>6b0b9d1e-7b43-4143-ba84-6bebf015a6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSvgIcon-root</value>
      <webElementGuid>ccb08563-3835-47c7-83f5-6241fa326a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a4bac60d-ce25-427b-b722-823ba2c0c65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>9d07b803-d7c9-41a7-990e-1fc2aa943dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>60dff63a-ae4c-4f30-9c72-a84fa705caae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>1.5</value>
      <webElementGuid>d94522a7-f27b-4287-a8fe-7c39d55d0b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mui-48657</value>
      <webElementGuid>68400a08-ce6a-4d0f-9b5f-123566260b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root jss631&quot;]/div[@class=&quot;jss637&quot;]/main[@class=&quot;jss643 jss644&quot;]/div[@class=&quot;MuiBox-root jss690 jss645&quot;]/div[@class=&quot;MuiPaper-root MuiCard-root jss691 MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-justify-content-xs-space-between&quot;]/div[@class=&quot;MuiGrid-root jss696&quot;]/button[@class=&quot;MuiButtonBase-root&quot;]/div[@class=&quot;MuiAvatar-root MuiAvatar-rounded jss695 MuiAvatar-colorDefault&quot;]/svg[@class=&quot;MuiSvgIcon-root&quot;]</value>
      <webElementGuid>0350410e-ac57-47c8-9bb0-d5aab49eac39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>4a09c5dd-e9db-4d2e-a6fe-4c0b770ec5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sản phẩm'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>cbc6f835-8fb9-497b-a622-3540de44b07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>c0323851-63c1-41b8-b0a6-d4229dc2c3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sắp xếp theo'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>f2d5e0a8-b38d-457c-8b59-edc7ae4e8ec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
